# Classification - Comparison of KNN, Logistic Regression, Decision Tree & SVM

In [1]:
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation

from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

import folium # plotting library

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
venues = pd.read_excel('venues.xlsx', index_col=0)

create one more column to identify spots to group data

In [3]:
# one hot encoding
onehot = pd.get_dummies(venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
onehot['Type'] = venues['Type'] 
onehot['Latitude'] = venues['Latitude']
onehot['Longitude'] = venues['Longitude']


In [4]:
onehot['dummyID'] = onehot['Latitude'].astype(str) + onehot['Longitude'].astype(str)

In [5]:
onehot['dummyID'].head()

0    22.28592192464961114.192492065819
1    22.28592192464961114.192492065819
2    22.28592192464961114.192492065819
3    22.28592192464961114.192492065819
4    22.28592192464961114.192492065819
Name: dummyID, dtype: object

In [6]:
# Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

grouped = onehot.groupby('dummyID').mean().reset_index()


In [7]:
grouped.head()

dummyID  Accessories Store  Airport  \
0  22.20868934294697114.0286954434421                0.0      0.0   
1  22.21905085835218114.2097986516457                0.0      0.0   
2  22.23211579304065114.1723792706762                0.0      0.0   
3     22.256529496435113.902582846465                0.0      0.0   
4  22.25832910621818114.1351251225447                0.0      0.0   

   Airport Food Court  Airport Gate  Airport Lounge  Airport Service  \
0                 0.0           0.0             0.0              0.0   
1                 0.0           0.0             0.0              0.0   
2                 0.0           0.0             0.0              0.0   
3                 0.0           0.0             0.0              0.0   
4                 0.0           0.0             0.0              0.0   

   Airport Terminal  American Restaurant  Amphitheater  Aquarium  Arcade  \
0               0.0             0.000000           0.0  0.000000     0.0   
1               0.0             0.026316           0.0  0.000000     0.0   
2               0.0             0.000000           0.0  0.117647     0.0   
3               0.0             0.000000           0.0  0.000000     0.0   
4               0.0             0.000000           0.0  0.000000     0.0   

   Arepa Restaurant  Argentinian Restaurant  Art Gallery  Art Museum  \
0               0.0                     0.0          0.0         0.0   
1               0.0                     0.0          0.0         0.0   
2               0.0                     0.0          0.0         0.0   
3               0.0                     0.0          0.0         0.0   
4               0.0                     0.0          0.0         0.0   

   Arts & Crafts Store  Asian Restaurant  Astrologer  Athletics & Sports  \
0                  0.0          0.043478         0.0            0.000000   
1                  0.0          0.000000         0.0            0.000000   
2                  0.0          0.000000         0.0            0.029412   
3                  0.0          0.000000         0.0            0.000000   
4                  0.0          0.000000         0.0            0.000000   

   Australian Restaurant  Auto Garage  BBQ Joint  Bagel Shop  Bakery  Bank  \
0                    0.0          0.0        0.0         0.0     0.0   0.0   
1                    0.0          0.0        0.0         0.0     0.0   0.0   
2                    0.0          0.0        0.0         0.0     0.0   0.0   
3                    0.0          0.0        0.0         0.0     0.0   0.0   
4                    0.0          0.0        0.0         0.0     0.0   0.0   

        Bar  Baseball Field  Basketball Court     Beach  Bed & Breakfast  \
0  0.000000             0.0               0.0  0.043478              0.0   
1  0.052632             0.0               0.0  0.026316              0.0   
2  0.000000             0.0               0.0  0.000000              0.0   
3  0.000000             0.0               0.0  0.000000              0.0   
4  0.000000             0.0               0.0  0.000000              0.0   

   Beer Bar  Beer Garden  Beer Store  Beijing Restaurant  Belgian Restaurant  \
0       0.0          0.0         0.0                 0.0                 0.0   
1       0.0          0.0         0.0                 0.0                 0.0   
2       0.0          0.0         0.0                 0.0                 0.0   
3       0.0          0.0         0.0                 0.0                 0.0   
4       0.0          0.0         0.0                 0.0                 0.0   

   Betting Shop  Bistro  Boat or Ferry  Bookstore  Border Crossing  \
0           0.0     0.0            0.0        0.0              0.0   
1           0.0     0.0            0.0        0.0              0.0   
2           0.0     0.0            0.0        0.0              0.0   
3           0.0     0.0            0.0        0.0              0.0   
4           0.0     0.0            0.0        0.0              0.0   

   Bota

Start classification

In [8]:
data = grouped
Y = data['Type']
X = data.drop(columns=['Type', 'Latitude', 'Longitude','dummyID'])

In [9]:
X.head()

Accessories Store  Airport  Airport Food Court  Airport Gate  \
0                0.0      0.0                 0.0           0.0   
1                0.0      0.0                 0.0           0.0   
2                0.0      0.0                 0.0           0.0   
3                0.0      0.0                 0.0           0.0   
4                0.0      0.0                 0.0           0.0   

   Airport Lounge  Airport Service  Airport Terminal  American Restaurant  \
0             0.0              0.0               0.0             0.000000   
1             0.0              0.0               0.0             0.026316   
2             0.0              0.0               0.0             0.000000   
3             0.0              0.0               0.0             0.000000   
4             0.0              0.0               0.0             0.000000   

   Amphitheater  Aquarium  Arcade  Arepa Restaurant  Argentinian Restaurant  \
0           0.0  0.000000     0.0               0.0                     0.0   
1           0.0  0.000000     0.0               0.0                     0.0   
2           0.0  0.117647     0.0               0.0                     0.0   
3           0.0  0.000000     0.0               0.0                     0.0   
4           0.0  0.000000     0.0               0.0                     0.0   

   Art Gallery  Art Museum  Arts & Crafts Store  Asian Restaurant  Astrologer  \
0          0.0         0.0                  0.0          0.043478         0.0   
1          0.0         0.0                  0.0          0.000000         0.0   
2          0.0         0.0                  0.0          0.000000         0.0   
3          0.0         0.0                  0.0          0.000000         0.0   
4          0.0         0.0                  0.0          0.000000         0.0   

   Athletics & Sports  Australian Restaurant  Auto Garage  BBQ Joint  \
0            0.000000                    0.0          0.0        0.0   
1            0.000000                    0.0          0.0        0.0   
2            0.029412                    0.0          0.0        0.0   
3            0.000000                    0.0          0.0        0.0   
4            0.000000                    0.0          0.0        0.0   

   Bagel Shop  Bakery  Bank       Bar  Baseball Field  Basketball Court  \
0         0.0     0.0   0.0  0.000000             0.0               0.0   
1         0.0     0.0   0.0  0.052632             0.0               0.0   
2         0.0     0.0   0.0  0.000000             0.0               0.0   
3         0.0     0.0   0.0  0.000000             0.0               0.0   
4         0.0     0.0   0.0  0.000000             0.0               0.0   

      Beach  Bed & Breakfast  Beer Bar  Beer Garden  Beer Store  \
0  0.043478              0.0       0.0          0.0         0.0   
1  0.026316              0.0       0.0          0.0         0.0   
2  0.000000              0.0       0.0          0.0         0.0   
3  0.000000              0.0       0.0          0.0         0.0   
4  0.000000              0.0       0.0          0.0         0.0   

   Beijing Restaurant  Belgian Restaurant  Betting Shop  Bistro  \
0                 0.0                 0.0           0.0     0.0   
1                 0.0                 0.0           0.0     0.0   
2                 0.0                 0.0           0.0     0.0   
3                 0.0                 0.0           0.0     0.0   
4                 0.0                 0.0           0.0     0.0   

   Boat or Ferry  Bookstore  Border Crossing  Botanical Garden  Boutique  \
0            0.0        0.0              0.0               0.0       0.0   
1            0.0        0.0              0.0               0.0       0.0   
2            0.0        0.0              0.0               0.0       0.0   
3            0.0        0.0              0.0               0.0       0.0   
4            0.0        0.0              0.0               0.0       0.0   

   Boxing Gym  Brazilian Res

In [10]:
from sklearn.neighbors import KNeighborsClassifier

### Train Test Split  
Out of Sample Accuracy is the percentage of correct predictions that the model makes on data that that the model has NOT been trained on. Doing a train and test on the same dataset will most likely have low out-of-sample accuracy, due to the likelihood of being over-fit.

It is important that our models have a high, out-of-sample accuracy, because the purpose of any model, of course, is to make correct predictions on unknown data. So how can we improve out-of-sample accuracy? One way is to use an evaluation approach called Train/Test Split.
Train/Test Split involves splitting the dataset into training and testing sets respectively, which are mutually exclusive. After which, you train with the training set and test with the testing set. 

This will provide a more accurate evaluation on out-of-sample accuracy because the testing dataset is not part of the dataset that have been used to train the data. It is more realistic for real world problems.


In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.2)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (229, 307) (229,)
Test set: (58, 307) (58,)


<div id="classification">
    <h2>Classification</h2>
</div>

<h3>K nearest neighbor (KNN)</h3>

#### Import library 

Classifier implementing the k-nearest neighbors vote.

In [30]:
from sklearn.neighbors import KNeighborsClassifier

### Training

Lets start the algorithm with k=4 for now:

In [31]:
k = 4
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=4, p=2,
           weights='uniform')

### Predicting
we can use the model to predict the test set:

In [32]:
yhat = neigh.predict(X_test)
yhat

array([2, 0, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2,
       2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 0, 2, 1, 2, 1, 2, 0, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 0, 2, 0])

### Accuracy evaluation
In multilabel classification, __accuracy classification score__ is a function that computes subset accuracy. This function is equal to the jaccard_similarity_score function. Essentially, it calculates how closely the actual labels and predicted labels are matched in the test set.

In [33]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.7292576419213974
Test set Accuracy:  0.6551724137931034


#### What about other K?
K in KNN, is the number of nearest neighbors to examine. It is supposed to be specified by the User. So, how can we choose right value for K?
The general solution is to reserve a part of your data for testing the accuracy of the model. Then chose k =1, use the training part for modeling, and calculate the accuracy of prediction using all samples in your test set. Repeat this process, increasing the k, and see which k is the best for your model.

We can calculate the accuracy of KNN for different Ks.

In [34]:
from sklearn.metrics import jaccard_similarity_score

Ks = 10
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))
jaccard = np.zeros((Ks-1))
ConfustionMx = [];
for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)
    jaccard[n-1] = jaccard_similarity_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc, std_acc, jaccard

(array([0.56896552, 0.56896552, 0.5862069 , 0.65517241, 0.62068966,
        0.62068966, 0.56896552, 0.60344828, 0.56896552]),
 array([0.06502569, 0.06502569, 0.06467003, 0.06241153, 0.06371191,
        0.06371191, 0.06502569, 0.06423267, 0.06502569]),
 array([0.56896552, 0.56896552, 0.5862069 , 0.65517241, 0.62068966,
        0.62068966, 0.56896552, 0.60344828, 0.56896552]))

<h2 id="modeling">Modeling (Logistic Regression with Scikit-learn)</h2>

Lets build our model using __LogisticRegression__ from Scikit-learn package. This function implements logistic regression and can use different numerical optimizers to find parameters, including ‘newton-cg’, ‘lbfgs’, ‘liblinear’, ‘sag’, ‘saga’ solvers. You can find extensive information about the pros and cons of these optimizers if you search it in internet.

The version of Logistic Regression in Scikit-learn, support regularization. Regularization is a technique used to solve the overfitting problem in machine learning models.
__C__ parameter indicates __inverse of regularization strength__ which must be a positive float. Smaller values specify stronger regularization. 
Now lets fit our model with train set:

In [35]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=1, solver='newton-cg').fit(X_train,y_train)
LR

/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

Now we can predict using our test set:

In [36]:
yhat = LR.predict(X_test)
yhat

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2])

__predict_proba__  returns estimates for all classes, ordered by the label of classes. So, the first column is the probability of class 1, P(Y=1|X), and second column is probability of class 0, P(Y=0|X):

In [37]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.30395098, 0.16149206, 0.53455696],
       [0.44011636, 0.1193144 , 0.44056924],
       [0.30958955, 0.17420437, 0.51620608],
       [0.30690925, 0.16709317, 0.52599757],
       [0.37528121, 0.1480464 , 0.47667239],
       [0.3004434 , 0.16719594, 0.53236066],
       [0.31100426, 0.16416484, 0.5248309 ],
       [0.39689428, 0.12945466, 0.47365106],
       [0.29160472, 0.1649687 , 0.54342658],
       [0.45189296, 0.11057813, 0.43752891],
       [0.31050458, 0.16161799, 0.52787743],
       [0.39307518, 0.12362521, 0.48329962],
       [0.53668373, 0.13236194, 0.33095433],
       [0.39614689, 0.13162532, 0.47222779],
       [0.32451298, 0.16439797, 0.51108905],
       [0.37073671, 0.14373323, 0.48553006],
       [0.33314368, 0.15594228, 0.51091404],
       [0.40662144, 0.1468528 , 0.44652576],
       [0.32427311, 0.15456472, 0.52116217],
       [0.46792283, 0.12581909, 0.40625808],
       [0.33756097, 0.15101289, 0.51142614],
       [0.38625478, 0.14242787, 0.47131735],
       [0.

<h2 id="evaluation">Evaluation</h2>

### jaccard index
Lets try jaccard index for accuracy evaluation. we can define jaccard as the size of the intersection divided by the size of the union of two label sets. If the entire set of predicted labels for a sample strictly match with the true set of labels, then the subset accuracy is 1.0; otherwise it is 0.0.



In [38]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

0.5

### log loss
Now, lets try __log loss__ for evaluation. In logistic regression, the output can be the probability of customer churn is yes (or equals to 1). This probability is a value between 0 and 1.
Log loss( Logarithmic loss) measures the performance of a classifier where the predicted output is a probability value between 0 and 1. 


In [39]:
from sklearn.metrics import log_loss
log_loss(y_test, yhat_prob)

1.0178327311520483

<hr>

<div id="modeling">
    <h2>Decisiuon Tree - Modeling</h2>
    We will first create an instance of the <b>DecisionTreeClassifier</b> called <b>tree</b>.<br>
    Inside of the classifier, specify <i> criterion="entropy" </i> so we can see the information gain of each node.
</div>

In [40]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion="entropy")
tree # it shows the default parameters

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

Next, we will fit the data with the training feature matrix <b> X_trainset </b> and training  response vector <b> y_trainset </b>

In [41]:
tree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

<hr>

<div id="prediction">
    <h2>Prediction</h2>
    Let's make some <b>predictions</b> on the testing dataset and store it into a variable called <b>predTree</b>.
</div>

In [42]:
predTree = tree.predict(X_test)

You can print out <b>predTree</b> and <b>y_testset</b> if you want to visually compare the prediction to the actual values.

<hr>

<div id="evaluation">
    <h2>Evaluation</h2>
    Next, let's import <b>metrics</b> from sklearn and check the accuracy of our model.
</div>

In [43]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, predTree))

DecisionTrees's Accuracy:  0.5517241379310345


__Accuracy classification score__ computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.  

In multilabel classification, the function returns the subset accuracy. If the entire set of predicted labels for a sample strictly match with the true set of labels, then the subset accuracy is 1.0; otherwise it is 0.0.


In [44]:
max_depth = 20
acc = np.zeros((max_depth-1))
jaccard = np.zeros((max_depth-1))
std_acc = np.zeros(max_depth-1)
for n in range(2,max_depth):
    
    #Train Model and Predict  
    tree = DecisionTreeClassifier(criterion="entropy", max_depth=n).fit(X_train,y_train)
    yhat=tree.predict(X_test)
    acc[n-1] = metrics.accuracy_score(y_test, yhat)
    jaccard[n-1] = jaccard_similarity_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

acc, std_acc, jaccard

(array([0.        , 0.63793103, 0.65517241, 0.51724138, 0.62068966,
        0.55172414, 0.55172414, 0.5862069 , 0.5       , 0.5       ,
        0.5       , 0.5       , 0.53448276, 0.55172414, 0.55172414,
        0.5       , 0.51724138, 0.51724138, 0.55172414]),
 array([0.        , 0.06310569, 0.06241153, 0.06561417, 0.06371191,
        0.06530098, 0.06530098, 0.06467003, 0.06565322, 0.06565322,
        0.06565322, 0.06565322, 0.0654969 , 0.06530098, 0.06530098,
        0.06565322, 0.06561417, 0.06561417, 0.06530098]),
 array([0.        , 0.63793103, 0.65517241, 0.51724138, 0.62068966,
        0.55172414, 0.55172414, 0.5862069 , 0.5       , 0.5       ,
        0.5       , 0.5       , 0.53448276, 0.55172414, 0.55172414,
        0.5       , 0.51724138, 0.51724138, 0.55172414]))

<h2> SVM with Scikit-learn</h2>

The SVM algorithm offers a choice of kernel functions for performing its processing. Basically, mapping data into a higher dimensional space is called kernelling. The mathematical function used for the transformation is known as the kernel function, and can be of different types, such as:

    1.Linear
    2.Polynomial
    3.Radial basis function (RBF)
    4.Sigmoid
Each of these functions has its characteristics, its pros and cons, and its equation, but as there's no easy way of knowing which function performs best with any given dataset, we usually choose different functions in turn and compare the results. Let's just use the default, RBF (Radial Basis Function) for this lab.

In [45]:
from sklearn import svm
from sklearn.metrics import f1_score

kernels = ['linear', 'poly', 'rbf', 'sigmoid',]
f1s = np.zeros(4)
js = np.zeros(4)

for i, k in enumerate(kernels):
    cls = svm.SVC(kernel=k).fit(X_train, y_train) 
    yhat = cls.predict(X_test)
    f1s[i] = f1_score(y_test, yhat, average='weighted') 
    js[i] = jaccard_similarity_score(y_test, yhat)

f1s, js

/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled

(array([0.45068966, 0.27750411, 0.27750411, 0.27750411]),
 array([0.53448276, 0.44827586, 0.44827586, 0.44827586]))

After running the 4 classification method, we deside to use KNN and k = 4